### ISSUE TITLE
If you let a dialog start while on a different virtual desktop, the dialog window is not drawn 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1296]
To continue with exotic reports ... the window is there, just not drawn, so you either have to mouse over some options or press enter in the case of continue windows — once you switch back to that window.
![image](https://user-images.githubusercontent.com/121515/122520368-cef43900-d013-11eb-8385-fd46c6c6d5d8.png)

It's not enough for the window to not have focus

**Comment by bradallred** [comment]
IIRC this is actually an SDL bug I saw fixed in git. SDL_Renderer doesn't draw when the renderer is "hidden" causing us to believe the window is not dirty when in fact it has to be completely redrawn.

The SDL folks were trying to be clever and efficient, but fail to realize this breaks down when rendering to a texture, which we are doing here. If updating to the tip of SDL doesn't fix it, I will open a bug with SDL about it.

we could (and may have to for things like `SDL_RENDER_TARGETS_RESET` and `SDL_RENDER_DEVICE_RESET`) add add support for application type events such as `SDL_APP_DIDENTERFOREGROUND` in our `EventManager` and `WindowManager` can just call `MarkDirty()` on all the windows whenever we gain focus.

**Comment by lynxlynxlynx** [comment]
Just noting this isn't fixed yet, though there's a nice TODO for SDL_RENDER_DEVICE_RESET present.

**Comment by MarcelHB** [comment]
But this seems to have relevance only for some corner-cases of D3D11, like having a driver updated _while_ running a game.

**Comment by bradallred** [comment]
I still think the fix lies in updating your libSDL2. If that doesn't fix it this is an issue that needs to be raised with SDL.

**Comment by lynxlynxlynx** [comment]
I can reproduce it with the buildbot build that now uses 2.0.12. But you were mentioning unreleased code, which I haven't tried.

**Comment by bradallred** [comment]
well the latest release is 2.0.16. I don't remember when that bug was resolved.

**Comment by lynxlynxlynx** [comment]
Can confirm it works on 2.0.20.
