### ISSUE TITLE
Cannot build on Mac using cmake if both sdls are installed

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1329]
The cmake build first failed trying to build the SDLAudio plugin because for some reason I haven't been able to work out it is being linked against both SDL1 and SDL2.

Removing the SDLAudio plugin just kicks the problem further down to SDLVideo where there are a bunch of errors about undeclared identifiers because our build is using SDL1 headers for an SDL2 build

```
-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected version: 0.9.0-git
-- Git version bool: 1
-- Performing Test VISIBILITY_HIDDEN
-- Performing Test VISIBILITY_HIDDEN - Success
-- Performing Test STACK_PROTECTOR
-- Performing Test STACK_PROTECTOR - Success
-- Performing Test FALLTHROUGH
-- Performing Test FALLTHROUGH - Success
-- Found PythonLibs: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libpython2.7.tbd (found suitable version "2.7.16", minimum required is "2.3") 
-- Looking for Python libraries and headers: found
-- Autodetecting SDL backend...
-- Found SDL: /Library/Frameworks/SDL.framework;-framework Cocoa (found version "1.2.16") 
-- Found SDL2: /Library/Frameworks/SDL2.framework;-framework Cocoa  
-- Found SDL 1.2, switching to SDL backend.
-- Found SDL 2.0, switching to SDL2 backend.
-- Could NOT find SDL2_mixer (missing: SDL2_MIXER_LIBRARIES SDL2_MIXER_INCLUDE_DIRS) 
-- Looking for SDL: found
-- Looking for libSDL: found
CMake Warning at CMakeLists.txt:336 (MESSAGE):
  Looking for SDL_mixer: not found!


CMake Warning at CMakeLists.txt:337 (MESSAGE):
  If you want to build the SDL_mixer plugin, install SDL_mixer first.


CMake Warning at CMakeLists.txt:338 (MESSAGE):
  Make sure you use a version compatible with the chosen SDL version.


-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libz.tbd (found version "1.2.11") 
-- Looking for Zlib: found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found OpenAL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenAL.framework  
-- Looking for OpenAL: found
CMake Warning at CMakeLists.txt:400 (MESSAGE):
  Looking for VLC: not found!


CMake Warning at CMakeLists.txt:401 (MESSAGE):
  If you want to build the VLC plugin, install VLC first.


-- Found Freetype: /usr/local/lib/libfreetype.dylib (found version "2.10.1") 
-- Looking for Freetype: found
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Success
-- Found ICONV: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libiconv.tbd  
-- Found ICONV includes: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include
-- One (and only one) of the ICONV_ACCEPTS_... tests must pass
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Success
-- Performing Test ICONV_ACCEPTS_CONST_INPUT
-- Performing Test ICONV_ACCEPTS_CONST_INPUT - Failed
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.37") 
-- Looking for libPNG: found
CMake Warning at CMakeLists.txt:445 (MESSAGE):
  Looking for Ogg Vorbis support: not found!


CMake Warning at CMakeLists.txt:446 (MESSAGE):
  While no original game data is in OGG format, some mod data is and will
  need conversion.


-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of int
-- Check size of int - done
-- Check size of long int
-- Check size of long int - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Looking for strndup
-- Looking for strndup - found
-- Looking for strlcpy
-- Looking for strlcpy - found
-- Looking for setenv
-- Looking for setenv - found
-- Looking for ldexpf
-- Looking for ldexpf - found
-- Looking for realpath
-- Looking for realpath - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for swab
-- Looking for swab - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - not found
-- Looking for include file langinfo.h
-- Looking for include file langinfo.h - found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Performing Test HAS_OBJALIGN4
-- Performing Test HAS_OBJALIGN4 - Success
-- Performing Test HAS_WSTRING
-- Performing Test HAS_WSTRING - Success
-- Performing Test PERMITS_OBJECT_TO_FUNCTION_CAST
-- Performing Test PERMITS_OBJECT_TO_FUNCTION_CAST - Failed
-- Copying SDL: /Library/Frameworks/SDL2.framework
-- Will link SDLVideo plugin to: /Users/brad/Projects/gemrb/build/gemrb/gemrb.app/Contents/MacOS/GemRB
-- 
-- These are the configured paths:
--   PREFIX: /usr/local
--   LIB_DIR: @loader_path/../Frameworks
--   PLUGIN_DIR: /Applications/gemrb.app/Contents/Plugins
--   BIN_DIR: /Applications
--   DATA_DIR: /Applications/gemrb.app/Contents/Resources
--   MAN_DIR: 
--   SYSCONF_DIR: 
--   DOC_DIR: /Applications/gemrb.app/Contents/Resources
--   ICON_DIR: 
--   SVG_DIR: 
--   MENU_DIR: 
-- 
-- Options:
--   LAYOUT: bundle
--   NOCOLOR: Yes
--   STATIC_LINK: disabled
--   INSOURCEBUILD: disabled
--   DISABLE_WERROR: disabled
--   WIN32_USE_STDIO: disabled
--   SDL_BACKEND: SDL2
--   OPENGL_BACKEND: None
-- 
-- Build type: RelWithDebInfo
-- Target bitness: 8*8
-- 
-- Compiler warnings are fatal.
-- If you hit one, let us know and rerun cmake with -DDISABLE_WERROR=1 to continue.
-- 
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:520 (ADD_LIBRARY):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /Users/brad/Projects/gemrb/gemrb/plugins/BAMImporter/BAMFontManager.cpp
Call Stack (most recent call first):
  gemrb/plugins/BAMImporter/CMakeLists.txt:1 (ADD_GEMRB_PLUGIN)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev):
  Policy CMP0068 is not set: RPATH settings on macOS do not affect
  install_name.  Run "cmake --help-policy CMP0068" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, the install_name fields for
  the following targets are still affected by RPATH settings:

   gemrb_core

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/brad/Projects/gemrb/build
```

**Comment by lynxlynxlynx** [comment]
Should be fixed now.

**Comment by bradallred** [comment]
no, I still get errors for undeclared identifiers due to using SDL1 headers when building SDL2 backend

**Comment by lynxlynxlynx** [comment]
Then it must be a problem in our ./cmake/modules/FindSDL2.cmake. What's the path to your SDL.h?

**Comment by bradallred** [comment]
`/Library/Frameworks/SDL.framework/Headers/SDL.h` for SDL 1 and `/Library/Frameworks/SDL2.framework/Headers/SDL.h`

**Comment by lynxlynxlynx** [comment]
How about now?

**Comment by bradallred** [comment]
no, I'm doubting its Mac specific.

```
-- Autodetecting SDL backend...
-- Found SDL2: /Library/Frameworks/SDL2.framework;-framework Cocoa  
-- Found SDL 2.0, switching to SDL2 backend.
-- Could NOT find SDL2_mixer (missing: SDL2_MIXER_LIBRARIES SDL2_MIXER_INCLUDE_DIRS) 
-- Looking for SDL: found
-- Looking for libSDL: found
CMake Warning at CMakeLists.txt:337 (MESSAGE):
  Looking for SDL_mixer: not found!


CMake Warning at CMakeLists.txt:338 (MESSAGE):
  If you want to build the SDL_mixer plugin, install SDL_mixer first.


CMake Warning at CMakeLists.txt:339 (MESSAGE):
  Make sure you use a version compatible with the chosen SDL version.

```

**Comment by lynxlynxlynx** [comment]
No, that's all fine, the two lib(SDL) found messages are shared by both backends. I do see on my system, and it's likely true for you as well though, that I do have also sdl1 vars in the cmake cache (`grep SDL.*_INC CMakeCache.txt`).

**Comment by bradallred** [comment]
the issue persists. is there something I should be doing other than recreating the build directory and running `cmake` inside it and then `make`?

**Comment by lynxlynxlynx** [comment]
Not at all. Can you post the logs and CMakeCache.txt of both runs somewhere?

**Comment by bradallred** [comment]
here is the output from cmake and the CMakeCache.txt:

[cmake.txt](https://github.com/gemrb/gemrb/files/8179975/cmake.txt)

[CMakeCache.txt](https://github.com/gemrb/gemrb/files/8179977/CMakeCache.txt)

**Comment by bradallred** [comment]
I can at least build again if I only have SDL2 installed, but the original issue persists

**Comment by lynxlynxlynx** [comment]
`SDL2_INCLUDE_DIR:PATH=/Library/Frameworks/SDL.framework/Headers`
Is the correct sdl2 one just with SDL2 in there?

**Comment by bradallred** [comment]
yes: /Library/Frameworks/SDL2.framework/Headers is the correct path

**Comment by lynxlynxlynx** [comment]
Does this help?
```diff
diff --git a/cmake/modules/FindSDL2.cmake b/cmake/modules/FindSDL2.cmake
index a706b86f8..3960d818f 100644
--- a/cmake/modules/FindSDL2.cmake
+++ b/cmake/modules/FindSDL2.cmake
@@ -69,15 +69,19 @@
 # (To distribute this file outside of CMake, substitute the full
 #  License text for the above reference.)
 
-find_path(SDL2_INCLUDE_DIR SDL.h
+find_path(SDL2_INCLUDE_DIR SDL2/SDL.h
   HINTS
     ENV SDLDIR
-  PATH_SUFFIXES include/SDL2 include Headers
   PATHS
-     ~/Library/Frameworks/SDL2.framework/
-     /Library/Frameworks/SDL2.framework/
      ~/Library/Frameworks/
      /Library/Frameworks/
+  NO_DEFAULT_PATH
+)
+# second call won't run if the first succeeded
+find_path(SDL2_INCLUDE_DIR SDL.h
+  HINTS
+    ENV SDLDIR
+  PATH_SUFFIXES include/SDL2 include
 )
 
 find_library(SDL2_LIBRARY_TEMP
```

**Comment by lynxlynxlynx** [comment]
Ah, got an even better idea, hold on.

**Comment by bradallred** [comment]
I can no longer build with SDL2 at all. It forces SDL1 and then fails to link SDLVideo.so

**Comment by bradallred** [comment]
I removed SDL1 to se what would happen and I get this interesting output:
```
-- Could NOT find SDL2 (missing: SDL2_DIR)
-- Could NOT find SDL (missing: SDL_LIBRARY) (found version "2.0.16")
```

**Comment by bradallred** [comment]
this is a [wider issue](https://github.com/Kitware/CMake/pull/149) that Kitware has [pushed onto SDL](https://github.com/libsdl-org/SDL/issues/4858)

**Comment by lynxlynxlynx** [comment]
That's only one of the possible files, eg. I have `/usr/lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config.cmake`. Is that not present or also not appropriate for our use case?

**Comment by lynxlynxlynx** [comment]
Actually where are your sdls from? The buildbot works, so the framework package from homebrew handles it fine.

**Comment by bradallred** [comment]
there is a framework package in homebrew? AFIK homebrew is for unix software so it builds everything the unix way. The frameworks come from libsdl.org or if you build SDL yourself on a Mac.

but speaking of macports, if there is a way to use that with GitHub we might want to consider it. Homebrew refuses to adopt universal (arm64+x86) binaries so we cannot produce a universal binary while using it. Not sure what our options are.

**Comment by lynxlynxlynx** [comment]
Probably not, I was just going off the frameworky code I had to modify.

macports are not preinstalled on the runners, but xcode is, so it looks doable: https://github.com/actions/virtual-environments/blob/macOS-11/20220220.1/images/macos/macos-11-Readme.md
https://www.macports.org/install.php
vcpkg also has mac support, but it looks like it can only produce separate binaries, not universal ones.

But it looks like a resurrection is needed any way, to make it buildable for apple users that want to use the official sdl builds.

**Comment by lynxlynxlynx** [comment]
Ok, so try again and we'll just add more fixes to the module if needed.

**Comment by bradallred** [comment]
starting with SDL 2.23 they finally provide an `sdl2-config.cmake` module so this can be built using `cmake -DSDL2_DIR=/Library/Frameworks/SDL2.framework  ..`
