### ISSUE TITLE
Windows build still broken 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1389]
CreateWindow is still a problem:
https://ci.appveyor.com/project/lynxlynxlynx/gemrb/builds/40165893#L439

There are some other errors further down, but at least 1 should be fixed by the same thing, since it's just a parsing problem.

**Comment by bradallred** [comment]
@MarcelHB was on the case

**Comment by MarcelHB** [comment]
Looking at Win right now and fixed a lot of things already, but I'm currently stuck on plugins and a linker error:
```
C:/Program Files/MSYS2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/AREImporter.dir/objects.a(AREImporter.cpp.obj): in function `GemRB::ImporterPlugin<GemRB::AREImporter>::ImporterPlugin()':
D:/Sources/gemrb/gemrb/core/Plugin.h:88: undefined reference to `__imp__ZTVN5GemRB14ImporterPluginINS_11AREImporterEEE'
C:/Program Files/MSYS2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/AREImporter.dir/objects.a(AREImporter.cpp.obj): in function `GemRB::ImporterPlugin<GemRB::AREImporter>::~ImporterPlugin()':
D:/Sources/gemrb/gemrb/core/Plugin.h:92: undefined reference to `__imp__ZTVN5GemRB14ImporterPluginINS_11AREImporterEEE'
C:/Program Files/MSYS2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/AREImporter.dir/objects.a(AREImporter.cpp.obj): in function `GemRB::ImporterPlugin<GemRB::AREImporter>::~ImporterPlugin()':
D:/Sources/gemrb/gemrb/core/Plugin.h:92: undefined reference to `__imp__ZTVN5GemRB14ImporterPluginINS_11AREImporterEEE'
```

that translates to: `__imp_vtable for GemRB::ImporterPlugin<GemRB::AREImporter>` but I haven't found the missing virtual or its missing definition ...

**Comment by bradallred** [comment]
this is clearly a bug in MSVC, but you should be able to work around it by adding a default destructor to `ImporterPlugin`

**Comment by MarcelHB** [comment]
That's GCC for me, and yes, that was also my first or second thought but that did not help yet.

I'm going to reproduce a minimal example later and try to find a fix.

**Comment by bradallred** [comment]
that error is utterly useless then. still seems like a compiler bug. you can clearly see the only virtual function for `ImporterPlugin` is the destructor which it inherits from `Plugin`

maybe those `Plugin` members need to be marked `noexcept` and `override`?

**Comment by lynxlynxlynx** [comment]
Or maybe try sticking GEM_EXPORT in more places, if it's just a default visibility problem.

**Comment by bradallred** [comment]
if that were true then we should have hit this ages ago. `Plugin` is already `GEM_EXPORT` (as is `ImporterPlugin`) and in the same file. `Held` is _not_ exported, but then why haven't we hit this before?

**Comment by MarcelHB** [comment]
`noexcept` makes no difference, although I guess it's better to have it then. `GEM_EXPORT Held` breaks tons of other things. Well, I guess I have to do it the hard way.

**Comment by bradallred** [comment]
`override` was the one I would have expected to at least spit out a better error.

**Comment by bradallred** [comment]
it [looks like](http://gcc.gnu.org/faq.html#vtables) the fix is to just change the destructor for `plugin`/'Held` to be `virtual ~... noexcept {}`

**Comment by MarcelHB** [comment]
By now I tried all this, but the linker still does not let me. Since it's all templates, this should be easy to reproduce with simple code, and without taking any other linker stuff into account, but no: works fine otherwise, just not here.

Maybe there is something I need to check in these macros of `plugindef.h` that can mess something up here.

**Comment by MarcelHB** [comment]
I had no luck today making GCC work with whatever I tried. Suspending this until weekend.

**Comment by MarcelHB** [comment]
The best thing I discovered to get _something_ forward is adding something like this in `AREImporter.cpp`
```cpp
namespace GemRB {
extern template class ImporterPlugin<AREImporter>;
}
```
But this only eliminates the errors around the destructor, leaving me with the constructor:
```
C:/Program Files/MSYS2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/AREImporter.dir/objects.a(AREImporter.cpp.obj): in function `GemRB::ImporterPlugin<GemRB::AREImporter>::ImporterPlugin()':
D:/Sources/gemrb/gemrb/core/Plugin.h:88: undefined reference to `__imp__ZTVN5GemRB14ImporterPluginINS_11AREImporterEEE'
```
I additionally tried replacing any `virtual ... = default` in the hierarchy by ` virtual ... {}` and so on, but this sticks.

@bradallred any other idea how this fits together?

**Comment by bradallred** [comment]
that depends. are you still trying to get the existing `Held`/`Holder` machinery to build, or is this happening with replacing that with `shared_ptr` as well?

Im still at a loss why the linker would complain about a missing symbol that is never used.

**Comment by MarcelHB** [comment]
No, I postponed getting rid of `Held` because it has a long tail of things that also need attention then (like having other things inheriting from `Plugin` with some explicit calls to `acquire` and `release` to these objects).

Damn, maybe I need to check if there are differences between the working Linux GCC/binutils and the ones from MSYS2.

**Comment by bradallred** [comment]
IMO it will be quicker/easier/better to just remove `Held` from plugins than to throw ourselves against the wall trying to find the arcane incantation to get it to compile. Plugins should be thread safe anyway and `Held` is not  TS while `shared_ptr` is. replacing `acquire` / `release` is easy: just delete them and it will work.

**Comment by MarcelHB** [comment]
With changes #1395, MSVC still complains about the abstract-instancing thing, and GCC is still not linking.

**Comment by bradallred** [comment]
hmmmm. have you tried separating the declaration from the assignment?

eg
`Holder<IMPORTER> importer = MakeHolder<IMPORTER>();`
to
`Holder<IMPORTER> importer;` + a ctor

**Comment by MarcelHB** [comment]
There is no more `Holder` there. And to make it work on MSVC, I specifically did this: https://github.com/gemrb/gemrb/pull/1395/commits/c3be4fd02a5c8f5b6c008d8d230db156cc869876

**Comment by bradallred** [comment]
sure, but my suggestion is relevant to `shared_ptr` too.

**Comment by MarcelHB** [comment]
No, this does not work as well from what I see. Feel free to test this at [my godbolt snippet](https://godbolt.org/z/zMcnc53aa).

**Comment by bradallred** [comment]
```
template <typename T>
std::shared_ptr<T> GetPluginHolder(PluginID id) {
	return std::static_ptr_cast<T>(PluginMgr::Get()->GetPlugin(id));
}

template <typename T>
Holder<T> GetImporter(PluginID id) {
	auto plugin = GetPluginHolder<T>(id);
	if (plugin) {
		return plugin->GetImporter();
	}
	return nullptr;
}

template <typename T>
Holder<T> GetImporter(PluginID id, DataStream* str) {
	auto plugin = GetPluginHolder<T>(id);
	if (plugin) {
		return plugin->GetImporter(str);
	}
	delete str;
	return nullptr;
}
```

does this not work? we dont need `MakeImporterPluginHolder` or `PluginHolder`

**Comment by bradallred** [comment]
we can inject SFINAE using `std::enable_if` and other tricks if we need to

**Comment by MarcelHB** [comment]
I guess not, since `PluginMgr` still works with raw pointers, and [std::static_pointer_cast](https://en.cppreference.com/w/cpp/memory/shared_ptr/pointer_cast) wants to have a shared pointer.

We can rework this, too.

**Comment by MarcelHB** [comment]
Well, in theory I made it work [like this](https://godbolt.org/z/h8E1G4zr4). But only MSVC is crashing internally with this code. 🤦‍♂️

**Comment by bradallred** [comment]
one thing we need to overcome with MSVC is that it considers `ResRef::operator[]` to be ambiguous with the built in subscript operator due to the implicit conversion to `const char*` operator we provide. The las several commits I've pushed up have been in an attempt to rid ourselves of the implicit conversion, but many users remain. I _think_ many should just be converted to take `const ResRef&` parameters, but it is hard to say. The main thing that stands out currently is creating/spawning creatures. those functions still take `const char*`.

**Comment by MarcelHB** [comment]
Good news: Clang + LLD was more helpful with respect to what is wrong: `lld-link: error: undefined symbol: __declspec(dllimport) vtable for GemRB::ImporterPlugin<GemRB::AREImporter>`

And this again can be fixed by adding `GEM_BUILD_DLL` in the respective `CMakeLists.txt`. I should have a PR soon.

**Comment by lynxlynxlynx** [comment]
The operator[] stuff is still broken:
```
C:\projects\gemrb\gemrb\core\Map.cpp(2936): error C2666: 'GemRB::ieVariable::operator []': 4 overloads have similar conversions [C:\projects\gemrb\gemrb\core\gemrb_core.vcxproj]
  c:\projects\gemrb\gemrb\includes\ie_types.h(84): note: could be 'char &GemRB::ieVariable::operator [](size_t) noexcept'
  c:\projects\gemrb\gemrb\includes\ie_types.h(80): note: or       'char GemRB::ieVariable::operator [](size_t) noexcept const'
  C:\projects\gemrb\gemrb\core\Map.cpp(2936): note: or       'built-in C++ operator[(const char *, int)'
  C:\projects\gemrb\gemrb\core\Map.cpp(2936): note: or       'built-in C++ operator[(char *, int)'
  C:\projects\gemrb\gemrb\core\Map.cpp(2936): note: while trying to match the argument list '(GemRB::ieVariable, int)'
```

It also complains about make_unique:
```
C:\projects\gemrb\gemrb\core\System\Logging.cpp(50): error C2668: 'GemRB::make_unique': ambiguous call to overloaded function [C:\projects\gemrb\gemrb\core\gemrb_core.vcxproj]
  C:\projects\gemrb\gemrb\includes\globals.h(348): note: could be 'std::unique_ptr<GemRB::Logger,std::default_delete<_Ty>> GemRB::make_unique<GemRB::Logger,std::deque<GemRB::Logger::WriterPtr,std::allocator<std::shared_ptr<GemRB::Logger::LogWriter>>>&>(std::deque<GemRB::Logger::WriterPtr,std::allocator<std::shared_ptr<GemRB::Logger::LogWriter>>> &)'
          with
          [
              _Ty=GemRB::Logger
          ]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\memory(2537): note: or       'std::unique_ptr<GemRB::Logger,std::default_delete<_Ty>> std::make_unique<GemRB::Logger,std::deque<GemRB::Logger::WriterPtr,std::allocator<std::shared_ptr<GemRB::Logger::LogWriter>>>&,0>(std::deque<GemRB::Logger::WriterPtr,std::allocator<std::shared_ptr<GemRB::Logger::LogWriter>>> &)' [found using argument-dependent lookup]
          with
          [
              _Ty=GemRB::Logger
          ]
  C:\projects\gemrb\gemrb\core\System\Logging.cpp(50): note: while trying to match the argument list '(std::deque<GemRB::Logger::WriterPtr,std::allocator<_Ty>>)'
          with
          [
              _Ty=GemRB::Logger::WriterPtr
          ]
```

**Comment by bradallred** [comment]
we already knew about `operator[]` and the fix for that was implemented in `FixedWidthString`, but `ieVariable` is not yet a `FixedWidthString`. PR #1401 would fix that.

I dont quite understand its complaint about `make_unique` tho. We only have one definition which forwards arguments, so I guess we have an ambiguous ctor for `Logger` or something

**Comment by bradallred** [comment]
oh, it looks like it considers `std::unique_ptr`, but that is only available in C++14 and later, so do we have the wrong compiler settings?

**Comment by bradallred** [comment]
it looks like it is in c++14 mode. even so I dont know why it would be ambiguous. we dont have a `using namespace std;` anywhere.

**Comment by lynxlynxlynx** [comment]
Let's just explicitly scope it then. Looks like it's on c++14 by default and doesn't provide a way to downgrade:
https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-160

Considering what a nightmare of a task #1404 is, can we move forward on #1401 some other way (but let's talk there)?

**Comment by lynxlynxlynx** [comment]
It doesn't like the nulling either:
```
C:\projects\gemrb\gemrb\core\Map.cpp(406): error C2668: 'GemRB::Bitmap::Bitmap': ambiguous call to overloaded function [C:\projects\gemrb\gemrb\core\gemrb_core.vcxproj]
  c:\projects\gemrb\gemrb\core\Bitmap.h(63): note: could be 'GemRB::Bitmap::Bitmap(const GemRB::Size &,const uint8_t *) noexcept'
  c:\projects\gemrb\gemrb\core\Bitmap.h(57): note: or       'GemRB::Bitmap::Bitmap(const GemRB::Size &,uint8_t)'
  C:\projects\gemrb\gemrb\core\Map.cpp(408): note: while trying to match the argument list '(GemRB::Size, char)'
```
Sounds like we need the reverse of a nullptr. Considering a 0 char triggered this, a suffixed 0 would likely trigger it just the same.

**Comment by bradallred** [comment]
AFICT, there is only one issue left, but I cannot understand why. I _know_ its valid to have a `std::vector` of a move only type, it's even `std::unique_ptr` now. It still tires to use the copy assignment operator when constructing the vector.

**Comment by bradallred** [comment]
This comment might be helpful later so I'm copying it here.

I tried std::pair in https://github.com/gemrb/gemrb/commit/730206eed8d1dd358ca5e69a62f9e099aa22ffc6 and it wasn't any more successful. what did move me past the ProjectileEntry issue MSVC was having was to add defaults for dtor/copy/move ops https://github.com/gemrb/gemrb/commit/c835d70501e4b6a78fadbe57cf4a9bd5219ddd6e. That didn't work for projectile, presumably because some child member of Projectile is causing them to be deleted.

FWIW this issue wold be much easier to diagnose if we had the full diagnostic from the compiler. All we get is the end result (same with the GitHub builders) its really annoying to just get "this class isn't nothrow movable" without the whole stack of issues leading up to it (we do get that its because the default move ctor is deleted, but not why). We need to know which member is causing issues. Its probably a simple fix like adding defaults for some stucts.

**Comment by bradallred** [comment]
a better option might be to update our builder to MSVC 19.28 which is the lowest version I could find that [works](https://godbolt.org/z/zcbnzaejb)

**Comment by lynxlynxlynx** [comment]
Appveyor has _Visual Studio Community 2019 version 16.11.9_, which I don't know if it is good enough, since MS uses so many different versions. It also has VS 2022, but I haven't checked platform support for that.

**Comment by MarcelHB** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B), that will be sufficient.

**Comment by lynxlynxlynx** [comment]
Let's see if that does the trick. We also need to update some docs like the link to the redistributable/runtime users have to install.

**Comment by lynxlynxlynx** [comment]
Now it breaks earlier with cmake not detecting sdl, while sdl2 is installed (2.0.4 though).

**Comment by MarcelHB** [comment]
Mixer is 2.0.4, SDL is 2.0.10. Anyway, I'm not sure if it's just for x86 present, and not x64? The README of the tool says 
> Note: This will install x86 libraries by default. To install x64, run: .\vcpkg\vcpkg install [package name]:x64-windows

I see traces of both platforms but nothing to say what we trying to compile actually.

**Comment by lynxlynxlynx** [comment]
2.0.20 actually, just not reflected on the website yet. I think the latest problem might be a cached 64-bit build of sdl2:
https://ci.appveyor.com/project/lynxlynxlynx/gemrb/builds/42531287

**Comment by lynxlynxlynx** [comment]
Ok, we're back to regular building errors:

```
EffectQueue.h(384,64): error C2338: EffectQueue should be noexcept MoveConstructible
```

```
C:\...\include\random(1863,5): error C2338: invalid template argument for uniform_int_distribution: N4659 29.6.1.1
[rand.req.genl]/1e requires one of short, int, long, long long, unsigned short, unsigned int, unsigned long, or unsigned long long
error C2338: note: char, signed char, unsigned char, char8_t, int8_t, and uint8_t are not allowed
```

**Comment by MarcelHB** [comment]
If so, maybe over some [flag](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-by-category?view=msvc-160#see-also), but playing around with that Godbolt example, none of the ones I've tried so far returned any better breakdown.

But yeah, it sounds like something else than vector vs list here, I'll play around a bit.

**Comment by lynxlynxlynx** [comment]
You could just comment out all uses of `children` in a PR to see if it does anything. If not, then the list isn't the problem.

**Comment by MarcelHB** [comment]
It probably is, but I expect it then not to make any difference if you say vector or list.

**Comment by bradallred** [comment]
right, I thought of jumping though hoops too :) It would be nice to not have to every time we want a straight answer from MSVC, but if thats the best option we have it'll certainly do the job.

**Comment by MarcelHB** [comment]
Ugh, yeah.

**Comment by bradallred** [comment]
trying to work this out with godbolt and PR #1561. no luck finding the issue yet.

**Comment by lynxlynxlynx** [comment]
I'd say you're making good progress, since now there are only linker errors in the log.

**Comment by bradallred** [comment]
sure, but its probably some foo with `GEM_EXPORT` that I dont know how to reconcile 🤷🏻‍♂️

**Comment by bradallred** [comment]
I don't understand Windows or why its dlls are so problematic, but maybe we just need to not allow dynamic linking for MSVC. somebody that knows how to fix it (if thats even possible) can send us a PR

**Comment by lynxlynxlynx** [comment]
We deliberately disabled static linking for windows ages ago (CMakeLists.txt:480), so I'm not sure that way is not anotehr "here be dragons" region.

Perhaps you're right and more GEM_EXPORTs need to be removed, like Marcel did earlier.

**Comment by MarcelHB** [comment]
No no, I centralized that `GEM_BUILD_DLL` so that all available `GEM_EXPORT` are signalling Win exporting everywhere when building dynamically.

I'll have a look, and otherwise I try that VS Build VM image soon.

**Comment by bradallred** [comment]
@MarcelHB appreciate it. send a PR to that "msvc" branch so we can integrate it there before merging into master.
