### ISSUE TITLE
[BG2 at least] Can't abort 'level up' window to postpone level up

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#799]
#### Description
When you enter 'level up' you can't close it (I didn't find how at least..) without attribute all remaining point and 'Accept'.

In original you can close window and postpone level up with 'Esc' key.

**Comment by lynxlynxlynx** [comment]
Yeah, would be annoying to implement, but of course technically possible.

**Comment by FrElvire** [comment]
It's OK :), but can make another problem more visible (same refresh problem as #739 ?) : 

open levelup windows
open special abilities window (don't select anything)
press 'esc'

It go back to level up window (perfect) but now special abilities button is greyed (should not).

The only solution left is to quit levelup window with 'esc' key as accept is rightfully greyed too.


So I don't know if this feature can be enabled without "refresh fix" (if this is really the problem)


if you want to do a quick test, a save with levelup needed (and special abilities for some)
[000000074-fin watcher keep - no dead.zip](https://github.com/gemrb/gemrb/files/4756662/000000074-fin.watcher.keep.-.no.dead.zip)

**Comment by FrElvire** [comment]
Now as #739 is fixed, this issue is perhaps easy to fix ?

**Comment by bradallred** [comment]
it is already fixed on that branch

**Comment by FrElvire** [comment]
> It's OK :), but can make another problem more visible (same refresh problem as #739 ?) :
> 
> open levelup windows
> open special abilities window (don't select anything)
> press 'esc'
> 
> It go back to level up window (perfect) but now special abilities button is greyed (should not).
> 
> The only solution left is to quit levelup window with 'esc' key as accept is rightfully greyed too.
> 
> So I don't know if this feature can be enabled without "refresh fix" (if this is really the problem)
> 
> if you want to do a quick test, a save with levelup needed (and special abilities for some)
> [000000074-fin watcher keep - no dead.zip](https://github.com/gemrb/gemrb/files/4756662/000000074-fin.watcher.keep.-.no.dead.zip)

Yes mostly :) , but this point is not fixed

**Comment by lynxlynxlynx** [comment]
I still don't know if it's safe, need to check for side-effects.

**Comment by lynxlynxlynx** [comment]
Yeah, this is a good way to cheat. You get more hp and lore and if the levelup would grant it, also improved saves and thac0.

I think it's best to just disable closing the window back. We need the new stats to be able to display the summary and it would be silly to refactor that with another mode to not do anything but just set a bunch of vars (and then do everything again on Accept).
