### ISSUE TITLE
[subviews] some store identify windows break

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#812]
Here's an error I get with the Dao merchant in bg2 ar2014:
```
[GUIScript/ERROR]: Runtime Error:                                                                       
[Python/ERROR]: Traceback (most recent call last):                                                      
[Python/ERROR]:   File "../gemrb/GUIScripts/MetaClasses.py", line 51, in __init__                       
[Python/ERROR]:     for k,v in kwargs.iteritems():                                                      
[Python/ERROR]: OverflowError: can't convert negative value to unsigned long                            
[GUIScript/ERROR]: Runtime Error:                                                                       
[Python/ERROR]: RuntimeError: Failed to call constructor                                                
[Python/ERROR]: Traceback (most recent call last):                                                      
[Python/ERROR]:   File "../gemrb/GUIScripts/GUISTORE.py", line 449, in <lambda>                         
[Python/ERROR]:     ScrollBar.SetEvent (IE_GUI_SCROLLBAR_ON_CHANGE, lambda: RedrawStoreIdentifyWindow(Window))                                                                                                  
[Python/ERROR]:   File "../gemrb/GUIScripts/GUISTORE.py", line 1346, in RedrawStoreIdentifyWindow       
[Python/ERROR]:     UpdateStoreCommon (Window, "STOTITLE", "STONAME", "STOGOLD")                        
[Python/ERROR]:   File "../gemrb/GUIScripts/GUISTORE.py", line 934, in UpdateStoreCommon                
[Python/ERROR]:     Label = Window.GetControlAlias (title)
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 219, in GetControlAlias
[Python/ERROR]:     return GetView(alias, self.ID)
[Python/ERROR]: RuntimeError: Failed to construct object
```

Same thing with the Tradeemet temple store. But the odd thing is that the Cutpurse's store from ar0500 around [793.2473] works fine.

**Comment by bradallred** [comment]
you mean this guy?
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/1126744/84614976-e8a0f480-ae84-11ea-8d0f-42cd72fb4bc9.png">

he works fine for me... didn't have issues in the temple either.

Furthermore, that first error seems like a bug in your Python or a bad stack trace.

```
for k,v in kwargs.iteritems():
```
is the first line of the Python object constructor where `kwargs` is this `PyObject`:
```
PyObject* kwargs = Py_BuildValue("{s:K}", "ID", id);
```
And the `"K"` format is for an `unsigned long long` and `id` is a `uint64_t`. I don't know where this conversion is allegedly happening, but it seems like there shouldn't be a conversion required at all since `Py_BuildValue` should be making us an unsigned integer object in the first place.

You can try manually constructing the dictionary with the appropriate python integer object instead of using `Py_BuildValue` or maybe rewriting the Python code to avoid `kwargs.iteritems()` since that seems to be triggering this mystery conversion.

**Comment by lynxlynxlynx** [comment]
No, that's the wrong area, it's the tent above this one. And only the identify window doesn't work.

**Comment by bradallred** [comment]
yeah, I have no problems with that window in either of those stores.

**Comment by lynxlynxlynx** [comment]
No, it happens on switch. I made a mistake though, the temple is fine as well.

Will inspect later, time for work. :)

**Comment by bradallred** [comment]
any news? I still haven't been able to see this.

**Comment by lynxlynxlynx** [comment]
Not yet, but it's on my list to dig in.

**Comment by lynxlynxlynx** [comment]
I now can't reproduce any python errors, however store window switching doesn't work, it's always stuck on the first displayed subwindow (usually item sale).

**Comment by bradallred** [comment]
that was broken in fcd2d43

**Comment by bradallred** [comment]
I've fixed that now if you want to try reproducing again.

**Comment by lynxlynxlynx** [comment]
I still have the same error. Tracked it down a bit further: InitStoreIdentifyWindow successfully does its thing and then the breakage starts once the CreateTopWinLoader runs the selection change handler. Which breaks on:

`ScrollBar.SetVarAssoc ("TopIndex", Count-ItemButtonCount) `

Which is really trying to do stuff with negatives, since in my case there's only 1 item present. I guess this is trying to scroll to the last item? Should be clamped to 0.
