### ISSUE TITLE
GLSL Shader error [GLES3 - Raspberry Pi4] 

### ISSUE THREAD

**Issue by cmitu** [gemrb/gemrb#932]
#### Description
(Originally reported [here](https://retropie.org.uk/forum/topic/26864/gemrb-support/22), by a RetroPie user. My initial diagnostic is not 100% correct there)

Trying to start GemRB on a Pi4, built with OpenGLES support and SDL2, leads to the following error during shader initialization:
```
...
Core]: Initializing GUI Script Engine...
[SDL 2 GL Driver]: Creating display
[SDL 2 GL Driver]: Creating Main Surface: w=1024 h=768 fmt=SDL_PIXELFORMAT_RGBA8888
[SDL 2 GL Driver/FATAL]: Can't build shader program: 0:1(1): error: syntax error, unexpected NEW_IDENTIFIER
...
```
 The reason I think it fails is because the shaders syntax is specific to the GLSL version corresponding to OpenGL(ES) 2.0 (GLSL 1.x), but are incorrect when the GLSL version resulting from the GL context initialization is higher (in this case is GLSL ES 3.10). 
 When the GL context is initialized here: https://github.com/gemrb/gemrb/blob/ac595aae4d4f0b735635d2c60e1af8d8aa64e75a/gemrb/plugins/SDLVideo/SDL20GLVideo.cpp#L50-L56

 the 2.0 version (ES or not) is requested, but the version requested is just a minimum guarantee, the resulting GL context can be different than OpenGL 2.0 (see https://wiki.libsdl.org/SDL_GLattr#OpenGL).
 
 In this particular case, adding a few debug lines to show the GL(SL) versions show:

* building with `-DOPENGL_BACKEND=GLES`, the GL context is created with GLES 3.1 and GLSL ES 3.10, GemRB fails with the aforementioned error:

```
  [Core]: Initializing GUI Script Engine...
  [SDL 2 GL Driver]: Creating display
  [SDL 2 GL Driver]: Creating Main Surface: w=1024 h=768 fmt=SDL_PIXELFORMAT_RGBA8888
  [SDL 2 GL Driver]: OpenGL version: OpenGL ES 3.1 Mesa 20.2.0-devel (git-e0518800a1), renderer: V3D 4.2, vendor: Broadcom
  [SDL 2 GL Driver]:   GLSL version: OpenGL ES GLSL ES 3.10
  [SDL 2 GL Driver/FATAL]: Can't build shader program: 0:1(1): error: syntax error, unexpected NEW_IDENTIFIER
```
My suspicion is that GLSL ES 3.10 doesn't like the `precision` line (deprecated in newer versions ?). 

* building with `-DOPENGL_BACKEND=OpenGL`, the GL context is created with OpenGL 2.1 and GLSL 1.20 and GemRB starts ok:

```
 [SDL 2 GL Driver]: OpenGL version: 2.1 Mesa 20.2.0-devel (git-e0518800a1), renderer: V3D 4.2s, vendor: Broadcom
 [SDL 2 GL Driver]:   GLSL version: 1.20
```

**GemRB version**: 0.8.7, but happens on `master` or previous versions also.

#### Reproducing
Test on a system supporting GLES 3.x (for instance on a Raspberry Pi 4, running the latest Raspbian/Raspberry Pi OS).

* build `0.8.7` or `master` with
```
-DCMAKE_BUILD_TYPE=Release -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2/ -DSDL_BACKEND=SDL2   -DCMAKE_INSTALL_PREFIX=/opt/retropie/ports/gemrb -DUSE_SDLMIXER=OFF -DOPENGL_BACKEND=GLES -DDISABLE_WERROR=1
```
* install
* try to run a game

#### Fix (?)

If the GLSL version is added in the shader code, the shaders are compiled and loaded fine, regardless of the OpenGL backend used.
I've tested with [this patch](https://github.com/cmitu/gemrb/commit/df493a7da7251eb5ea33b62a65580d09b440dd74) and it seems ok.

**Comment by lynxlynxlynx** [comment]
Great analysis, thanks for looking into it. With the next release our GL setup will change (perhaps even dropping the pure GL backends), but until that happens, let's have a fixed master. Please submit the fix as a PR.

**Comment by bradallred** [comment]
You might want to also test the subviews branch and open issues/PRs if there is an issue there. The rendering on that branch is completely different.

**Comment by cmitu** [comment]
@bradallred I can certainly give it a try - are the build instructions similar ?

**Comment by lynxlynxlynx** [comment]
The same. :)

**Comment by cmitu** [comment]
OK, I used the `subviews` branch and it works fine on the Pi4 (using OpenGL 2.1).
I see that GLES is no longer a selection for `OPENGL_BACKEND` and only the "opengl" SDL_Renderer is supported. That works for the Pi4, the older models don't have (by default) support for OpenGL, just for OpenGLES 2.1, so I guess they can use the non-GL path.

**Comment by lynxlynxlynx** [comment]
On master, the older ones were unusable with plain SDL2 rendering, but IIRC this was improved on subviews, so perhaps it will be ok.

@bradallred something like this would be useful (just edit this comment):
Backend changes from master:
| backend | subviews | notes
----------- | ------------ | -------
SDL1 | no change | soon to not be default any more
SDL2 | faster | most (only?) noticeable on macos?
SDL2, GL | ? |
SDL2,  GL ES | dropped |

**Comment by bradallred** [comment]
seems like something handy for the wiki page so [added it there](https://github.com/gemrb/gemrb/wiki/Subviews---Origins-and-Summary-of-Changes#video-driver-notes).

Plain SDL2 should be loads faster now, but I don't know if the older Pi used hardware acceleration or just software so I have no idea what to expect.

SDL2 supports `opengles2` as a rendering backend, so it is quite possible that adding support for OpenGLES2 would be only a few lines of code. We just would need an additional `#define` for differentiating the 2 in only one place where we select the SDL2 renderer to use. The shader code is quite simple and should work for both, but if not then its just a matter of copying them and tweaking the code for GLES and adding another `#ifdef` (or config) for the shader paths

**Comment by cmitu** [comment]
> Plain SDL2 should be loads faster now, but I don't know if the older Pi used hardware acceleration or just software so I have no idea what to expect.

Other PI models can certainly use HW acceleration, if you want to use/support it.

Commit https://github.com/gemrb/gemrb/commit/acd885b11ac18db97837653815ab91212480721f attempts to improve the RPI detection, but it's not enough for Pi models < 4, that use the Broadcom GLES driver (instead of Mesa) for hardware accelerated GLES. Trying to build `0.8.7` (with `OPENGL_BACKEND=GLES` ) fails during linking, since the the correct libraries are not linked - the `SDLVideo` plugin is linked only with the OpenGL libraries 

https://github.com/gemrb/gemrb/blob/5780f194a37f2c6a6ec25d5e56437409f0b61e55/gemrb/plugins/SDLVideo/CMakeLists.txt#L4-L14

I intend to open another issue for this (build) issue, just haven't got the time to find a proper solution.

> SDL2 supports opengles2 as a rendering backend, so it is quite possible that adding support for OpenGLES2 would be only a few lines of code. 

If I remove the restriction for `RenderDriver == opengl`, and force the `opengles2` render driver, then I stumble into something similar to the issue at hand, so maybe a similar approach (shader versioning or conditional loading based in GL renderer detected) could work.
```
$ SDL_RENDER_DRIVER=opengles2 /opt/retropie/ports/gemrb/bin/gemrb -C /opt/retropie/configs/ports/baldursgate2/GemRB.cfg
...
[SDL20Video/DEBUG]: Renderer: opengles2
[SDL 2 GL Driver]: OpenGL version: OpenGL ES 3.1 Mesa 20.2.0-devel (git-e0518800a1), renderer: V3D 4.2, vendor: Broadcom
[SDL 2 GL Driver]:   GLSL version: OpenGL ES GLSL ES 3.10
[SDL 2 GL Driver/FATAL]: Can't build shader program: 0:2(1): error: No precision specified in this scope for type `vec2'
0:10(1): error: No precision specified in this scope for type `vec4'
0:15(1): error: No precision specified in this scope for type `vec2'

[Core/FATAL]: Cannot initialize shaders.
```

**Comment by bradallred** [comment]
> Other PI models can certainly use HW acceleration, if you want to use/support it.

No, I meant support from `SDL_Renderer` not our code.

> error: No precision specified in this scope for type `vec2'

This is probably easily fixed. Just add the `precision` for GLES2. Our `GLSLProgram` class has checks to remove it for plain OpenGL. Should work in theory.

**Comment by bradallred** [comment]
I've committed changes to _theoretically_ support GLES2...

**Comment by cmitu** [comment]
There's still not support in the build part (`-DOPENGL_BACKEND=GLES`), if I read the CMakeLists.txt file correctly, `OPENGL_BACKEND` gets set to 1 regardless of what I choose with `cmake`

https://github.com/gemrb/gemrb/blob/2d099ee3e2d656005acf774b0dfa2fa68ec918fa/CMakeLists.txt#L321-L324

Regardless, the context hinting in SDL20Video.cpp works and an `opengles2` context is created, but then the test below fails and GemRB bails out.

 https://github.com/gemrb/gemrb/blob/2d099ee3e2d656005acf774b0dfa2fa68ec918fa/gemrb/plugins/SDLVideo/SDL20Video.cpp#L97-L102

**Comment by lynxlynxlynx** [comment]
Ah, that cmake line needs to be nuked as well. We have code elsewhere to make sure the define is passed on. Feel free to submit a PR, also for differentiating the backend string.

**Comment by bradallred** [comment]
I've fixed the comparison

**Comment by bradallred** [comment]
@cmitu any updates on wether or not this works?

**Comment by cmitu** [comment]
@bradallred Yes and no.

I have prepared a PR (based on the `subviews` branch) that would better tackle the OpenGLES detection/compilation for `cmake` and also adjust the codepaths (`#define`) in the source.
The problem is the new [SDLTextureV..glsl](https://github.com/gemrb/gemrb/blob/subviews/gemrb/plugins/SDLVideo/Shaders/SDLTextureV.glsl) is not compatible with neither of the GLES GLSL versions supported by the Pi4, because of the lack of some built-ins:
```
[SDL20Video/DEBUG]: Renderer: opengles2
[SDL 2 GL Driver]: OpenGL version: OpenGL ES 3.1 Mesa 20.2.0-devel (git-e0518800a1), renderer: V3D 4.2, vendor: Broadcom
[SDL 2 GL Driver]:   GLSL version: OpenGL ES GLSL ES 3.10
[SDL 2 GL Driver/FATAL]: Can't build shader program: 0:7(15): error: `gl_ModelViewProjectionMatrix' undeclared
0:7(46): error: `gl_Vertex' undeclared
0:7(15): error: operands to arithmetic operators must be numeric
0:8(11): error: `gl_Color' undeclared
0:9(19): error: `gl_MultiTexCoord0' undeclared
0:9(14): error: cannot construct `vec2' from a non-numeric data type
```

From what I found, `gl_ModelViewProjectionMatrix` (and possibly other built-ins) are no longer available after GLSL 1.20 (~= Open GL 2.1) and not present in the earlier GLSL ES version (1.00). 
 
I'll submit the PR I have right now as a draft, but, as it stands, GLES would not run because of that particular shader construct.

**Comment by lynxlynxlynx** [comment]
Sounds like it wouldn't be that hard to replace, though I don't know if this then breaks any important backwards compatibility:
https://stackoverflow.com/questions/21980947/replacement-for-gl-position-gl-modelviewprojectionmatrix-gl-vertex

**Comment by cmitu** [comment]
I submitted my changed in https://github.com/gemrb/gemrb/pull/936, but forgot to set it as Draft.

**Comment by bradallred** [comment]
I didn't write `SDLTextureV` btw. I shamelessly copied it from SDL itself, so worst case we can steal the EGL2 equivalent from them as well and just select the right one depending on `OPENGL_BACKEND`

**Comment by bradallred** [comment]
this appears to me to be the equivalent:

```
  uniform mat4 u_projection;
    attribute vec2 a_position;
    attribute vec2 a_texCoord;
    attribute vec2 a_angle;
    attribute vec2 a_center;
    varying vec2 v_texCoord;
 
    void main()
    { 
        float s = a_angle[0]; 
        float c = a_angle[1] + 1.0;
        mat2 rotationMatrix = mat2(c, -s, s, c);
        vec2 position = rotationMatrix * (a_position - a_center) + a_center;
        v_texCoord = a_texCoord;
        gl_Position = u_projection * vec4(position, 0.0, 1.0);
        gl_PointSize = 1.0;
    } 
```

**Comment by cmitu** [comment]
Unfortunately I don't have any GLSL knowledge to add any modifications to the shader/OpenGL code.
@bradallred I can re-test if you add any changes to the shader and see how it works with GLES3/GLES2.

**Comment by bradallred** [comment]
I have no real GLSL knowledge either, but I'm sure I can fumble around and cobble something together.

Annoyingly, SDL refuses to give me a gles2 renderer even tho macOS supports GLES2 just fine. I'll have to get the iOS port running in the simulator again so I can test it out. I'll be out of town for about 3 weeks tho so its going to be some time before I get around to that experiment.

**Comment by bradallred** [comment]
the only real important bit is the `varying vec2 v_texCoord` and setting it. Looks like the old `Sprite32.glsf` shader would work fine too, but we would have to set `s_texture` in some way or change it to some other equivalent (probably just hard code it to 0).

@MarcelHB maybe you have other/better ideas?

**Comment by MarcelHB** [comment]
An _idea_: https://www.khronos.org/opengles/sdk/tools/Reference-Compiler/

I do not have an OpenGL ES3.0 device but I can try to find something that reduces the ping-pong of testing cross-compatibility a bit.

**Comment by bradallred** [comment]
I believe we need ES2.0, not 3.0. SDL doesnt _Seem_ to support ES3.

**Comment by MarcelHB** [comment]
We cannot simply port the same shader from my research:

- We can prepend `#version 100\n precision mediump float;` for OpenGL ES, and `#version 110` for desktops.
- We get rid of `gl_ModelViewProjectionMatrix` by simply assuming that we always have unity matrix.
- But I cannot see a way to get the stencil coordinates portably this way, i. e. replacing `gl_MultiTexCoord0`. It works in OpenGL because of `glTexCoord` being used by SDL2, but there is no such thing in OpenGL ES 2.0, and thus nothing in its GLSL. Not sure what OpenGL ES 1.0 is doing, that looks different again.

We can probably use the shader you extracted from the SDL2 OpenGL ES2 renderer, and only there, as we can eliminate the only uniform variable `u_projection` over assuming a unity matrix (or you re-set it additionally). The rest of the `attribute`s should still be bound, but I cannot test this.

**Comment by bradallred** [comment]
yes, we will need to bind some attributes, but this should be a one time setup AFIK.

**Comment by lynxlynxlynx** [comment]
Let's continue in #938.
